server:
  port: 8080

spring:
  datasource:
    username: root
    password: v3J6YHPK
    url: jdbc:mysql://47.103.203.62:3306/12306
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:cn/train/mapper/*Mapper.xml
  type-aliases-package: cn.train.entity

#showSql
logging:
  level:
    cn:
      train:
        mapper: debug